# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False)),
                ('comm', models.TextField()),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userEmail', models.CharField(max_length=30)),
                ('userImg', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=0)),
                ('confirmed', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.User'),
        ),
    ]
