# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userEmail', models.CharField(max_length=30)),
                ('userImg', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=0)),
                ('confirmed', models.BooleanField(default=0)),
            ],
        ),
    ]
